stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH


.deploy:
  interruptible: true
  image: registry.kriese.eu/jobs/docker/base@sha256:2cff6c5aa23abece09b92114d1d71a108c758b1adc9d3bf3ba99624ed26bfc25
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - rsync -aPhh --chmod=D775,F664 --delete ./dist/ --exclude-from=.rsyncignore gitlab@vps577063.ovh.net:/opt/docker/html/de.pusle-med-nanni.${CI_ENVIRONMENT_SLUG}/
  needs:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true

build:
  interruptible: true
  stage: build
  image: ghcr.io/visualon/builder:3.1.41@sha256:623d03a15fb589e24e1acbb0e238518a624939927ec5d4cb3f01a0cf0fbc65d4
  cache:
    - key: ${CI_COMMIT_REF_SLUG}-build
      paths:
        - dist/
    - key:
        prefix: node-deps
        files:
          - yarn.lock
      paths:
        - .yarn/cache
  before_script:
    - install-apt graphicsmagick
    - yarn install
  script:
    - yarn build
    - find dist/images/ -type f -iname '*.jpg' -not -name '*.thumb*' -delete
  artifacts:
    paths:
      - dist
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy_dev:
  extends: .deploy
  environment:
    name: dev
    url: https://dev.pusle-med-nanni.de
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy_prod:
  extends: .deploy
  environment:
    name: www
    url: https://www.pusle-med-nanni.de


pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  needs:
    - build
