stages:
  - build
  - deploy

.deploy:
  interruptible: true
  image: registry.kriese.eu/jobs/docker/base@sha256:1eebe3f942f3eacf1ad238b30cd8ac498550fbd79cd8184b7513789c3314927b
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - rsync -aPhh --chmod=D775,F664 --delete ./dist/ --exclude-from=.rsyncignore gitlab@vps577063.ovh.net:/opt/docker/html/de.pusle-med-nanni.${CI_ENVIRONMENT_SLUG}/
  only:
    - main

build:
  interruptible: true
  stage: build
  image: ghcr.io/visualon/node:14.17.0
  variables:
    YARN_CACHE_FOLDER: '.yarn-cache'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - node_modules/
      - .yarn-cache
      - dist/
  before_script:
    - apk add --no-cache graphicsmagick git
    - yarn install --frozen-lockfile
  script:
    - yarn build
    - find dist/images/ -type f -iname '*.jpg' -not -name '*.thumb*' -delete
  artifacts:
    paths:
      - dist

deploy_dev:
  extends: .deploy
  environment:
    name: dev
    url: https://dev.pusle-med-nanni.de

deploy_prod:
  extends: .deploy
  environment:
    name: www
    url: https://www.pusle-med-nanni.de
  when: manual

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  when: manual
  only:
    - main
