stages:
  - build
  - deploy

.deploy:
  interruptible: true
  image: registry.kriese.eu/jobs/docker/base@sha256:58b1202459dc95952ddd2726b911aa426609f2a5e179a3c4379fd0bb7267eb63
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - rsync -aPhh --chmod=D775,F664 --delete ./dist/ --exclude-from=.rsyncignore gitlab@vps577063.ovh.net:/opt/docker/html/de.pusle-med-nanni.${CI_ENVIRONMENT_SLUG}/
  only:
    - master

build:
  interruptible: true
  stage: build
  image: node:12.18.4-alpine@sha256:f667be05181f5bc13cc8ff1dac8b0ffb9198e98f3d6562342ef44255087a584c
  variables:
    YARN_CACHE_FOLDER: '.yarn-cache'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - node_modules/
      - .yarn-cache
      - dist/
  before_script:
    - apk add --no-cache graphicsmagick git
    - yarn install --frozen-lockfile
  script:
    - yarn build
    - find dist/images/ -type f -iname '*.jpg' -not -name '*.thumb*' -delete
  artifacts:
    paths:
      - dist

deploy_dev:
  extends: .deploy
  environment:
    name: dev
    url: https://dev.pusle-med-nanni.de

deploy_prod:
  extends: .deploy
  environment:
    name: www
    url: https://www.pusle-med-nanni.de
  when: manual

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  when: manual
  only:
    - master
