image: node:carbon-alpine


variables:
  YARN_CACHE_FOLDER: ".yarn-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn-cache
    - bower_components/

before_script:
  - apk add --no-cache git graphicsmagick
  - yarn install --pure-lockfile
  - npx bower install --allow-root

build:
  tags:
    - prod
  script:
    - yarn build
    - docker build -t "pusle-med-nanni/www:${CI_COMMIT_REF_SLUG}" .
