
stages:
  - build
  - deploy


# before_script:
#   - apk add --no-cache git graphicsmagick openssh-client rsync

#   - eval $(ssh-agent -s)
#   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh

#   - ssh-keyscan vps577063 >> ~/.ssh/known_hosts
#   - chmod 644 ~/.ssh/known_hosts

#   - yarn install --pure-lockfile
#   - npx bower install --allow-root

build:
  stage: build
  image: node:lts-alpine
  variables:
    YARN_CACHE_FOLDER: '.yarn-cache'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - node_modules/
      - .yarn-cache
      - bower_components/
  before_script:
    - apk add --no-cache graphicsmagick git
    - yarn install --pure-lockfile
    - npx bower install --allow-root
  script:
    - yarn build
    - find public/images/ -type f -iname '*.jpg' -not -name '*.thumb*' -delete
  artifacts:
    paths:
      - public

deploy_dev:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client rsync

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan vps577063 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - rsync -aPhh --chmod=D775,F664 --delete ./public/ --exclude-from=.rsyncignore gitlab@vps577063:/opt/docker/html/de.pusle-med-nanni.${CI_ENVIRONMENT_SLUG}/
  environment:
    name: dev
    url: https://dev.pusle-med-nanni.de
  only:
    - master

deploy_prod:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client rsync

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan vps577063 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -aPhh --chmod=D775,F664 --delete ./public/ --exclude-from=.rsyncignore gitlab@vps577063:/opt/docker/html/de.pusle-med-nanni.dev/
  environment:
    name: prod
    url: https://www.pusle-med-nanni.de
  when: manual
  only:
    - master

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  when: manual
  only:
    - master
