name: deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  deploy:
    runs-on: ubuntu-24.04

    needs:
      - build

    environment:
      name: www
      url: https://www.pusle-med-nanni.de

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Setup SOPS
        uses: nhedger/setup-sops@18e52f363488ed469d2e1855e542a1c651743bba # v3.0.0

      - name: prepare
        run: |
          ./bin/prepare.sh
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      - name: Download pages artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pages
          path: dist

      - name: deploy
        run: |
          rsync -aPc --stats --chmod=D775,F664 --delete ./dist/ --exclude-from=.rsyncignore gitlab@vps577063.ovh.net:/opt/docker/html/de.pusle-med-nanni.www/

      - name: cleanup
        if: ${{ always() }}
        run: |
          ssh-agent -k
