name: test

on:
  push:
    branches-ignore:
      - main
      - gh-readonly-queue/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
